services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000