version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: competetion-front
    env_file:
      - .env
    ports:
      - "3010:3010"
      - "81:80"
    volumes:
      - .:/app  # Mount your application code into the container
