version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: competetion-front
    ports:
      - 3010:3010
    volumes:
      - .:/app  # Mount your application code into the container
#    command: ["node", "app/.output/server/index.mjs"]
